server:
  port: 8020
spring:
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
logging:
  level:
    com.koreait.exam.chat_app_24_04: debug